---
services:
  restic-exporter:
    image: restic-exporter:custom
    container_name: restic-exporter
    environment:
      - TZ=Europe/Madrid
      - RESTIC_REPOSITORY=rest:http://diego:cKFwz4pNgSo3kj@192.168.10.191:8888/
      - RESTIC_PASSWORD=rS45Tgt2eJw3Vc
      # - RESTIC_PASSWORD_FILE=/file_with_password_here
#      - RESTIC_REPOSITORY=s3:http://10.0.2.15:9002/restic
#      - AWS_ACCESS_KEY_ID=oR5BtezJSXP0fPOi
#      - AWS_SECRET_ACCESS_KEY=dnNtGQIfxDWdmFljUrHDHEYjHpEwf1o7
#      - RESTIC_PASSWORD=rS45Tgt2eJw3Vc
      - REFRESH_INTERVAL=1800 # 30 min
#    volumes:
#      - /host_path/restic/data:/data
    ports:
      - "8001:8001"
    restart: unless-stopped
